"""empty message

Revision ID: a30fe8b3de0f
Revises: 71aec4f1c359
Create Date: 2020-10-02 15:07:55.585548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30fe8b3de0f'
down_revision = '71aec4f1c359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trades_ticker_key', 'trades', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('trades_ticker_key', 'trades', ['ticker'])
    # ### end Alembic commands ###
