"""empty message

Revision ID: 71aec4f1c359
Revises: 965ccb4a13c4
Create Date: 2020-09-29 10:58:55.949031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71aec4f1c359'
down_revision = '965ccb4a13c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###
