"""added column to watchlist

Revision ID: 965ccb4a13c4
Revises: aeb96cc08176
Create Date: 2020-09-28 12:17:03.717262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965ccb4a13c4'
down_revision = 'aeb96cc08176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlists', 'name')
    # ### end Alembic commands ###
